-- OrçaFácil MVP schema
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  company_name text not null default 'Minha empresa',
  phone text,
  logo_url text,
  plan text not null default 'free' check (plan in ('free','pro')),
  plan_status text,
  subscription_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create sequence if not exists public.proposal_number_seq start 1001;

create table if not exists public.proposals (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  public_token uuid not null default gen_random_uuid() unique,
  number text not null default ('OF-' || to_char(now(), 'YYYY') || '-' || lpad(nextval('public.proposal_number_seq')::text, 5, '0')),
  client_name text not null,
  client_email text,
  client_phone text,
  title text not null,
  introduction text,
  status text not null default 'draft' check (status in ('draft','sent','accepted','rejected','expired')),
  currency text not null default 'BRL',
  valid_until date,
  payment_terms text,
  notes text,
  subtotal numeric(14,2) not null default 0,
  discount numeric(14,2) not null default 0,
  total numeric(14,2) not null default 0,
  responded_by_name text,
  responded_by_email text,
  sent_at timestamptz,
  viewed_at timestamptz,
  accepted_at timestamptz,
  rejected_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists proposals_user_created_idx on public.proposals(user_id, created_at desc);
create index if not exists proposals_public_token_idx on public.proposals(public_token);
create index if not exists proposals_user_sent_idx on public.proposals(user_id, sent_at);

create table if not exists public.proposal_items (
  id uuid primary key default gen_random_uuid(),
  proposal_id uuid not null references public.proposals(id) on delete cascade,
  description text not null,
  quantity numeric(14,3) not null check (quantity > 0),
  unit_price numeric(14,2) not null check (unit_price >= 0),
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists proposal_items_proposal_idx on public.proposal_items(proposal_id, sort_order);

create table if not exists public.proposal_events (
  id bigint generated by default as identity primary key,
  proposal_id uuid not null references public.proposals(id) on delete cascade,
  event_type text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists proposal_events_proposal_idx on public.proposal_events(proposal_id, created_at desc);

create table if not exists public.subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  provider text not null,
  provider_subscription_id text not null,
  status text not null,
  plan text not null default 'pro',
  amount numeric(14,2),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(provider, provider_subscription_id)
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, full_name, company_name)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    coalesce(nullif(new.raw_user_meta_data ->> 'company_name', ''), 'Minha empresa')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.proposals enable row level security;
alter table public.proposal_items enable row level security;
alter table public.proposal_events enable row level security;
alter table public.subscriptions enable row level security;

-- O cliente web usa apenas Auth. O acesso às tabelas passa pelo backend com service role.
-- Portanto, não criamos policies de leitura/escrita para anon/authenticated no MVP.

revoke all on public.profiles from anon, authenticated;
revoke all on public.proposals from anon, authenticated;
revoke all on public.proposal_items from anon, authenticated;
revoke all on public.proposal_events from anon, authenticated;
revoke all on public.subscriptions from anon, authenticated;
